### PR TITLE
Resolve Cyclic Reference Issue

### PR DESCRIPTION
**Pull request by adamgfraser**
Initial work on resolving cyclic reference issue. This compiles but a few tests are timing out. Based on my initial investigation it appears that these tests are just running slowly and actually timing out, versus there being some issue with using the test clock versus the live clock. I had initially thought this was related to the `sized` combinator for generators but I fixed that, added an additional test, and am still seeing the issue. I'm not sure why just moving code into the same file would impact performance in this way.

### CODE REVIEW

**Comment by adamgfraser** [comment]
Okay. Scala 2.11 tests are now passing CI but I had to increase the default timeout. Also somehow there is an issue with finding the `TestMain` class on Scala 2.13. Trying to fix that now but that seems like a much more tactical issue. Still not sure how just moving objects from separate files into one is causing such a performance regression.

**Comment by jdegoes** [comment]
@adamgfraser Curious, does it impact all of them or just 2.11?

**Comment by jdegoes** [comment]
Thanks for your work on this, nearly there!

**Comment by adamgfraser** [comment]
@jdegoes It looks like we have an issue where source files in the `jvm` directory aren't being compiled on Scala 2.13. For example, if you put some nonsense code in `FiberRefSpecJvm` and then do `./sbt`, `++2.13.1`, `project coreTestsJVM`, and `test:compile` it compiles without errors. That's why the tests are failing on 2.13 JVM right now. I think may be related to some of the changes to `BuildHelper.scala`. Trying to track down.

**Comment by adamgfraser** [comment]
Example of failed test with default 60 second global timeout:

```
[info] - StreamChunkSpec
[info]   - StreamChunk.map
[info] Timeout of 1 m exceeded.
[info]   - StreamChunk.filterNot
[info] Timeout of 1 m exceeded.
```

https://circleci.com/gh/zio/zio/49715?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

In this case everything passed on 2.11 and it was actually on 2.12 that the tests timed out. Tests seem to pass if timeout is increased to 120 seconds.

I looked at these tests and they rely on property based testing but beyond that doesn't seem to be anything particularly remarkable about them (other tests that didn't time out use the same generators, though maybe they took longer too). But tests clearly pass if given enough time. I don't really understand how but could accessing the environment be less efficient this way and because generators are repeatedly accessing the environment the problem is more salient?

**Pull request merged**
